<a href="https://colab.research.google.com/github/Tsyhankova/goit_python/blob/main/HW7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Задание 1**


In [81]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier

wine_dataset = load_wine()

Разделите wine_dataset на обучающую и тестовую выборки.

In [29]:
X, y = load_wine(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X, y)

Обучите модель на тренировочной выборке и оцените ее качество на тестовой.

# **RidgeClassifier**

In [34]:
rig_cls = RidgeClassifier().fit(X_train, y_train)
rig_cls.score(X, y)

0.9887640449438202

In [35]:
y_pred_rig = rig_cls.predict(X_test)
y_pred_rig == y_test

array([ True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

# **LogisticRegression**

In [26]:
logistic_regressor = LogisticRegression(max_iter=3000).fit(X_train, y_train)
logistic_regressor.score(X, y)

0.9775280898876404

In [27]:
y_pred_log = logistic_regressor.predict(X_test)
y_pred_log == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True])

Попробуйте повторить шаги 3 и 4 разбив датасет на обучающую и тестовую выборки в какой-то собственной пропорции. Как это отразилось на качестве модели?

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [72]:
rig_cls = RidgeClassifier().fit(X_train, y_train)
y_pred_rig = rig_cls.predict(X_test)
y_pred_rig == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [73]:
rig_cls.score(X, y)

1.0

In [74]:
logistic_regressor = LogisticRegression(max_iter=6000).fit(X_train, y_train)
y_pred_log = logistic_regressor.predict(X_test)
y_pred_log == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [75]:
logistic_regressor.score(X, y)

0.9943820224719101

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [77]:
rig_cls = RidgeClassifier().fit(X_train, y_train)
y_pred_rig = rig_cls.predict(X_test)
y_pred_rig == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [78]:
rig_cls.score(X, y)

0.9943820224719101

In [79]:
logistic_regressor = LogisticRegression(max_iter=5000).fit(X_train, y_train)
y_pred_log = logistic_regressor.predict(X_test)
y_pred_log == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True])

In [80]:
logistic_regressor.score(X, y)

0.9775280898876404

При увеличении обучающей выборки, модель показывает лучше результат.
Класс RidgeClassifier обучился чуть лучше, чем LogisticRegression на данном датасете.

# **Задание 2**

Постройте линейный классификатор подобно тому, как мы это делали в задании 1 на датасете Ириса Фишера.

In [92]:
from sklearn.datasets import load_iris

In [101]:
X, y = load_iris(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [102]:
rig_cls = RidgeClassifier().fit(X_train, y_train)
y_pred_rig = rig_cls.predict(X_test)
y_pred_rig == y_test

array([ True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
        True, False,  True, False,  True])

In [103]:
rig_cls.score(X, y)

0.8533333333333334

In [104]:
from sklearn.neighbors import KNeighborsClassifier

In [105]:
kn_cls = KNeighborsClassifier().fit(X_train, y_train)
y_pred_kn = kn_cls.predict(X_test)
y_pred_kn == y_test 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True])

In [106]:
kn_cls.score(X, y)

0.9666666666666667

In [107]:
clf_log = LogisticRegression(random_state=0, max_iter = 5000).fit(X_train, y_train)
y_pred_log = clf_log.predict(X_test)
y_pred_log == y_test 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [108]:
clf_log.score(X, y)

0.9733333333333334

# Задание **3**

In [209]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression

In [210]:
data_diab = load_diabetes()
data_diab.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [225]:
y = data_diab['target']
y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

In [212]:
X, y = load_diabetes(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [213]:
lin_reg = LinearRegression().fit(X_train, y_train)
lin_reg.score(X, y)

0.5151643310693095

Проверка точности прогнозов по r2 Scores (Коэффициент детерминации)


In [214]:
from sklearn.metrics import r2_score

y_pred_lin = lin_reg.predict(X_test)
r2_score(y_test, y_pred_lin)

0.5766857486397609

Root Mean Square Error

In [215]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred_lin)
rmse = np.sqrt(mse)
rmse

53.228236266066766

In [216]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101)

In [217]:
lin_reg = LinearRegression().fit(X_train, y_train)
lin_reg.score(X, y)

0.510811145402116

Проверка точности прогнозов по r2 *Scores*

In [218]:
y_pred_lin = lin_reg.predict(X_test)
r2_score(y_test, y_pred_lin)

0.45767674177195583

Root Mean Square Error

In [219]:
mse = mean_squared_error(y_test, y_pred_lin)
rmse = np.sqrt(mse)
rmse

58.009275047551995

In [220]:
from sklearn.linear_model import SGDRegressor 

In [222]:
sgd_reg = SGDRegressor(max_iter = 10900).fit(X_train, y_train)
sgd_reg.score(X, y)

0.5118834004098051

Проверка точности прогнозов по r2 *Scores*

In [223]:
y_pred_sgd = sgd_reg.predict(X_test)
r2_score(y_test, y_pred_sgd)

0.4807542696560606

Root Mean Square Error

In [224]:
mse = mean_squared_error(y_test, y_pred_sgd)
rmse = np.sqrt(mse)
rmse

56.761621063274234

SGDRegressor немного лучше сработал на данной выборке при пропорциях 30% к 70% и random_state = 101, чем LinearRegression. LinearRegression сработала хуже при заданных мной пропорциях.